<a href="https://colab.research.google.com/github/SatyamRaj1/Pytorch_for_DL/blob/main/Pytorch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


# Introduction To Tensors

#### Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
MATRIX  = torch.tensor([[7, 8],
                        [2, 3]])
MATRIX

tensor([[7, 8],
        [2, 3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([2, 3])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[3, 2, 6, 7],
                        [2, 3, 5, 7]],
                       [[1, 2, 4, 9], [2, 1, 4, 44]],
                       ])
TENSOR


tensor([[[ 3,  2,  6,  7],
         [ 2,  3,  5,  7]],

        [[ 1,  2,  4,  9],
         [ 2,  1,  4, 44]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 2, 4])

In [ ]:
TENSOR[0]

tensor([[3, 2, 6, 7],
        [2, 3, 5, 7]])

### Nomenclature
- scalar and vector are represented usually in lower case
- matrix and tensors are represented as capital letters


### Random Tensors
Used to initialise weights

In [ ]:
#creating a random tensor of size/shape (3, 4)
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.2042, 0.7340, 0.0796, 0.1897],
         [0.5613, 0.7262, 0.3401, 0.6701],
         [0.4394, 0.4459, 0.0574, 0.4740]],

        [[0.4432, 0.5784, 0.2422, 0.1745],
         [0.3809, 0.6635, 0.5437, 0.6276],
         [0.3556, 0.8783, 0.9032, 0.1701]]])

In [ ]:
#creating a random tensor with similiar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# zero tensor
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
#use torch range
one_to_ten = torch.arange(start = 0, end = 10, step = 2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
# tensors like (of same shape)
five_zeros = torch.zeros_like(input=one_to_ten)
five_zeros

tensor([0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** tensor not right datatype (tensor.dtype) /shape(tensor.shape) /on right device(tensor.device) --> common error for incorrect datatype


In [ ]:
int_64_tensor = torch.tensor([3, 5, 7, 8])
int_64_tensor, int_64_tensor.dtype

(tensor([3, 5, 7, 8]), torch.int64)

In [ ]:
float_32_tensor = torch.tensor([3.0, 5, 7.2, 8])
float_32_tensor, float_32_tensor.dtype

(tensor([3.0000, 5.0000, 7.2000, 8.0000]), torch.float32)

In [ ]:
float_32_tensor_2 = torch.tensor([3.0, 5.1, 7, 8], dtype = None)
float_32_tensor_2, float_32_tensor_2.dtype

(tensor([3.0000, 5.1000, 7.0000, 8.0000]), torch.float32)

In [ ]:
float_16_tensor = torch.tensor([3, 5, 7, 8], dtype = torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 5., 7., 8.], dtype=torch.float16), torch.float16)

In [ ]:
int_tensor = torch.tensor([3, 5, 2, 5],
                          dtype = None #datatype
                          , device=None, #device - 'cpu' / 'cuda'(gpu) if two tensors are not on same device then error
                          requires_grad=False #track gradient with tensor operations
                          )

In [ ]:
float_16_tensor_typecast = float_32_tensor.type(torch.float16)
float_16_tensor_typecast, float_16_tensor_typecast.dtype

(tensor([3.0000, 5.0000, 7.1992, 8.0000], dtype=torch.float16), torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9.0000, 25.0000, 50.4000, 64.0000])

In [ ]:
float_32_tensor*int_64_tensor

tensor([ 9.0000, 25.0000, 50.4000, 64.0000])

In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9094, 0.2581, 0.5022, 0.3534],
        [0.3782, 0.0641, 0.5403, 0.5813],
        [0.9592, 0.3317, 0.7805, 0.9548]])

In [ ]:
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Tensor Manipulation
* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matrix Multiplication


In [ ]:
operation_tensor = torch.tensor([1, 2, 3, 5])
#addition
operation_tensor+10

tensor([11, 12, 13, 15])

In [ ]:
operation_tensor*10

tensor([10, 20, 30, 50])

In [ ]:
operation_tensor-10

tensor([-9, -8, -7, -5])

In [ ]:
torch.mul(operation_tensor, 10)

tensor([10, 20, 30, 50])

In [ ]:
operation_tensor/2

tensor([0.5000, 1.0000, 1.5000, 2.5000])

In [ ]:
 second_operation_tensor = torch.tensor([2, 8, 9, 11])
 second_operation_tensor*operation_tensor

tensor([ 2, 16, 27, 55])

In [ ]:
%%time
# @ is symbol of matmul/mm(alias)
torch.matmul(second_operation_tensor, operation_tensor)


CPU times: user 282 µs, sys: 45 µs, total: 327 µs
Wall time: 2.34 ms


tensor(100)

In [ ]:
%%time
result = 0
for i in range(4):
  result+= operation_tensor[i]*second_operation_tensor
result

CPU times: user 575 µs, sys: 0 ns, total: 575 µs
Wall time: 644 µs


tensor([ 22,  88,  99, 121])

Inbuilt method takes less time

Shape error:
For matrix multiplication:
1. **inner dimensions** should match
  * (3, 2) @ (3, 2) error
  * (2, 3) @ (3, 2) work
  * (3, 2) @ (2, 3) work
2. Result matrix has shape of outer dimensions

In [ ]:
#Transpose
matrix1 = torch.rand(3, 2)
matrix1

tensor([[0.2339, 0.3385],
        [0.9695, 0.9546],
        [0.1754, 0.1819]])

In [ ]:
matrix1.T

tensor([[0.2339, 0.9695, 0.1754],
        [0.3385, 0.9546, 0.1819]])

### Tensor Aggregation
find min, max, mean, sum, etc.

In [ ]:
m1 = torch.arange(2, 50, 5)
torch.min(m1), torch.max(m1), torch.sum(m1)

(tensor(2), tensor(47), tensor(245))

In [ ]:
torch.mean(m1)
#here gives datatype error so need to typecast

RuntimeError: ignored

In [ ]:
torch.mean(m1, dtype = torch.float32)

tensor(24.5000)

In [ ]:
torch.mean(m1.type(torch.float32))

tensor(24.5000)

In [ ]:
m1.sum() #can do like this also

tensor(245)

In [ ]:
#position min/max -> get min/max index
m1.argmin(), m1.argmax()

(tensor(0), tensor(9))

### Reshaping, Stacking, Squeezing and Unsqueezing Tensors
* Reshaping - reshape an input tensor to a defined shape
* view - return a view of input tensor of a certain shape but the same memory as original tensor
* combining multiple tensors on top of each other(vstack) or side by side(hstack)
* Squeeze - remove all `1` dimensions(dimension of size 1) from a tensor<br>
  Example - `A*1*B*C*1*D -> A*B*C*D`
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add extra dimension
x_reshaped = x.reshape(1, 9) #dimension should match so that it can be matched
#notice extra dimension has been added 2 brackets
x_reshaped_2 = x.reshape(9, 1)
x_reshaped, x_reshaped_2

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [ ]:
z = x.view(1, 9)
z, z.shape #although it appears similiar to reshape it shares same memory with original tensor

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# so changing view changes original tensor as they share smae memory
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensors on top of each other
x_stack = torch.stack([x, x, x, x],dim = 0)
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#hstack
torch.stack([x, x, x, x], dim = 1)

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
 #torch squeeze
 x_squeeze = torch.squeeze(x_reshaped)
#  or by x_reshaped.squeeze()
 x_reshaped.shape, x_squeeze, x_squeeze.shape

(torch.Size([1, 9]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [ ]:
# unsqueeze adds a single dimension to a target tensor at a specific dim (dimension)
x_squeeze.unsqueeze(dim = 1), x_squeeze.unsqueeze(dim = 0)

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
#returns a view so change in view will result in change in original
Image = torch.rand(size = (224, 224, 3))
Image_permuted = Image.permute(2, 0, 1) #0th dim is previous 2nd dim, 1st is prev 0th and so on...
Image_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
ex = torch.rand(size = (2, 4, 3))
ex2 = ex.permute(2, 0, 1)
ex

tensor([[[0.3021, 0.7444, 0.6821],
         [0.4139, 0.9937, 0.7620],
         [0.2273, 0.0060, 0.9781],
         [0.4619, 0.9076, 0.7473]],

        [[0.1172, 0.2158, 0.1659],
         [0.0476, 0.0701, 0.3991],
         [0.3770, 0.7971, 0.6465],
         [0.4119, 0.7816, 0.5741]]])

In [ ]:
ex2

tensor([[[0.3021, 0.4139, 0.2273, 0.4619],
         [0.1172, 0.0476, 0.3770, 0.4119]],

        [[0.7444, 0.9937, 0.0060, 0.9076],
         [0.2158, 0.0701, 0.7971, 0.7816]],

        [[0.6821, 0.7620, 0.9781, 0.7473],
         [0.1659, 0.3991, 0.6465, 0.5741]]])

In [ ]:
    ex2[0][0][0]= 5 #or ex2[0, 0, 0]
    ex2

tensor([[[5.0000, 0.4139, 0.2273, 0.4619],
         [0.1172, 0.0476, 0.3770, 0.4119]],

        [[0.7444, 0.9937, 0.0060, 0.9076],
         [0.2158, 0.0701, 0.7971, 0.7816]],

        [[0.6821, 0.7620, 0.9781, 0.7473],
         [0.1659, 0.3991, 0.6465, 0.5741]]])

In [ ]:
ex #change in original

tensor([[[5.0000, 0.7444, 0.6821],
         [0.4139, 0.9937, 0.7620],
         [0.2273, 0.0060, 0.9781],
         [0.4619, 0.9076, 0.7473]],

        [[0.1172, 0.2158, 0.1659],
         [0.0476, 0.0701, 0.3991],
         [0.3770, 0.7971, 0.6465],
         [0.4119, 0.7816, 0.5741]]])

In [ ]:
#Indexing
#use `:` to get everything
ex[:, :, 1]

tensor([[0.7444, 0.9937, 0.0060, 0.9076],
        [0.2158, 0.0701, 0.7971, 0.7816]])

### Numpy and Tensors
* numpy to tensor -> `torch.from_numpy(nparray)`
* tensor to numpy -> `torch.Tensor.numpy(tensorArray)`

In [6]:
npArray = np.arange(1.0, 9.0)
tensor = torch.from_numpy(npArray)
#Warning : default numpy datatype is float64 whereas tensor is float 32 (pytorch reflects default datatype of numpy)
npArray, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [8]:
onesTensor = torch.ones(8)
numpyfromTensor = torch.Tensor.numpy(onesTensor)
onesTensor, numpyfromTensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take random out of )
To reduce the randomness in neural networks and PyTorch comes the concept of a
**random seed**.

In [13]:
Seed = 42
torch.manual_seed(Seed)

rt1 = torch.rand(3, 3)
rt2 = torch.rand(3, 3)
#whenever we run this cell everytime same rand no. (note rt1!=rt2)
rt1, rt2

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739]]))

In [14]:
#if we want same tensor
torch.manual_seed(Seed)

rt1 = torch.rand(3, 3)
torch.manual_seed(Seed)
rt2 = torch.rand(3, 3)
rt1, rt2

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]))

# Set Up GPU

In [1]:
#Check GPU
!nvidia-smi

Tue Nov 14 21:49:57 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8    13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
#count no. of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [6]:
#create a tensor (by default on cpu)
tensor = torch.arange(1.0, 8.0)
tensor, tensor.device

(tensor([1., 2., 3., 4., 5., 6., 7.]), device(type='cpu'))

In [10]:
#move tensor to gpu (if available)
tensorGpu = tensor.to(device) #device earlier setup as cuda if available
tensorGpu
#:0 index of GPU as only 1 so index 0

tensor([1., 2., 3., 4., 5., 6., 7.], device='cuda:0')

In [11]:
# Moving tensors to CPU (if tensor is on GPU can't transform to numpy)
tensorGpu.numpy()

TypeError: ignored

In [13]:
tensorCPU = tensorGpu.cpu().numpy()
tensorCPU

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)